//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionHouseClient.AuctionHouseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfWebApplication")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BidCustomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidCustomPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BidPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BidTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RatingPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidCustomName {
            get {
                return this.BidCustomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BidCustomNameField, value) != true)) {
                    this.BidCustomNameField = value;
                    this.RaisePropertyChanged("BidCustomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidCustomPhone {
            get {
                return this.BidCustomPhoneField;
            }
            set {
                if ((this.BidCustomPhoneField.Equals(value) != true)) {
                    this.BidCustomPhoneField = value;
                    this.RaisePropertyChanged("BidCustomPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BidPrice {
            get {
                return this.BidPriceField;
            }
            set {
                if ((this.BidPriceField.Equals(value) != true)) {
                    this.BidPriceField = value;
                    this.RaisePropertyChanged("BidPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BidTimestamp {
            get {
                return this.BidTimestampField;
            }
            set {
                if ((this.BidTimestampField.Equals(value) != true)) {
                    this.BidTimestampField = value;
                    this.RaisePropertyChanged("BidTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RatingPrice {
            get {
                return this.RatingPriceField;
            }
            set {
                if ((this.RatingPriceField.Equals(value) != true)) {
                    this.RatingPriceField = value;
                    this.RaisePropertyChanged("RatingPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bid", Namespace="http://schemas.datacontract.org/2004/07/WcfWebApplication")]
    [System.SerializableAttribute()]
    public partial class Bid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomName {
            get {
                return this.CustomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNameField, value) != true)) {
                    this.CustomNameField = value;
                    this.RaisePropertyChanged("CustomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomPhone {
            get {
                return this.CustomPhoneField;
            }
            set {
                if ((this.CustomPhoneField.Equals(value) != true)) {
                    this.CustomPhoneField = value;
                    this.RaisePropertyChanged("CustomPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuctionHouseServiceReference.IAuctionHouseService")]
    public interface IAuctionHouseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetAllProducts", ReplyAction="http://tempuri.org/IAuctionHouseService/GetAllProductsResponse")]
        System.Collections.Generic.List<AuctionHouseClient.AuctionHouseServiceReference.Product> GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetAllProducts", ReplyAction="http://tempuri.org/IAuctionHouseService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AuctionHouseClient.AuctionHouseServiceReference.Product>> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetProduct", ReplyAction="http://tempuri.org/IAuctionHouseService/GetProductResponse")]
        AuctionHouseClient.AuctionHouseServiceReference.Product GetProduct(int itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetProduct", ReplyAction="http://tempuri.org/IAuctionHouseService/GetProductResponse")]
        System.Threading.Tasks.Task<AuctionHouseClient.AuctionHouseServiceReference.Product> GetProductAsync(int itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/BidOnProduct", ReplyAction="http://tempuri.org/IAuctionHouseService/BidOnProductResponse")]
        void BidOnProduct(AuctionHouseClient.AuctionHouseServiceReference.Bid bid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/BidOnProduct", ReplyAction="http://tempuri.org/IAuctionHouseService/BidOnProductResponse")]
        System.Threading.Tasks.Task BidOnProductAsync(AuctionHouseClient.AuctionHouseServiceReference.Bid bid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuctionHouseServiceChannel : AuctionHouseClient.AuctionHouseServiceReference.IAuctionHouseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuctionHouseServiceClient : System.ServiceModel.ClientBase<AuctionHouseClient.AuctionHouseServiceReference.IAuctionHouseService>, AuctionHouseClient.AuctionHouseServiceReference.IAuctionHouseService {
        
        public AuctionHouseServiceClient() {
        }
        
        public AuctionHouseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuctionHouseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionHouseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionHouseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AuctionHouseClient.AuctionHouseServiceReference.Product> GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AuctionHouseClient.AuctionHouseServiceReference.Product>> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public AuctionHouseClient.AuctionHouseServiceReference.Product GetProduct(int itemNumber) {
            return base.Channel.GetProduct(itemNumber);
        }
        
        public System.Threading.Tasks.Task<AuctionHouseClient.AuctionHouseServiceReference.Product> GetProductAsync(int itemNumber) {
            return base.Channel.GetProductAsync(itemNumber);
        }
        
        public void BidOnProduct(AuctionHouseClient.AuctionHouseServiceReference.Bid bid) {
            base.Channel.BidOnProduct(bid);
        }
        
        public System.Threading.Tasks.Task BidOnProductAsync(AuctionHouseClient.AuctionHouseServiceReference.Bid bid) {
            return base.Channel.BidOnProductAsync(bid);
        }
    }
}
